/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    noticias: Noticia;
    reunioes: Reunioe;
    resolucoes: Resolucoe;
    editais: Editai;
    entidades: Entidade;
    'rede-protecao': RedeProtecao;
    depoimentos: Depoimento;
    destaques: Destaque;
    faq: Faq;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    noticias: NoticiasSelect<false> | NoticiasSelect<true>;
    reunioes: ReunioesSelect<false> | ReunioesSelect<true>;
    resolucoes: ResolucoesSelect<false> | ResolucoesSelect<true>;
    editais: EditaisSelect<false> | EditaisSelect<true>;
    entidades: EntidadesSelect<false> | EntidadesSelect<true>;
    'rede-protecao': RedeProtecaoSelect<false> | RedeProtecaoSelect<true>;
    depoimentos: DepoimentosSelect<false> | DepoimentosSelect<true>;
    destaques: DestaquesSelect<false> | DestaquesSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    configuracoes: Configuracoe;
    'pagina-inicial': PaginaInicial;
    indicadores: Indicadore;
  };
  globalsSelect: {
    configuracoes: ConfiguracoesSelect<false> | ConfiguracoesSelect<true>;
    'pagina-inicial': PaginaInicialSelect<false> | PaginaInicialSelect<true>;
    indicadores: IndicadoresSelect<false> | IndicadoresSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Blog do conselho. Salve como rascunho e publique quando aprovado.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticias".
 */
export interface Noticia {
  id: number;
  title: string;
  /**
   * Gerado automaticamente a partir do título. Edite apenas se necessário — altera a URL pública.
   */
  slug?: string | null;
  categoria: 'noticia' | 'conferencia' | 'evento' | 'gestao' | 'fmdca' | 'orientacao' | 'nota-tecnica';
  /**
   * Chamada curta exibida nas listagens e no compartilhamento.
   */
  resumo?: string | null;
  corpo?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Opcional. Sem capa, usamos uma ilustração autoral (campo Tema).
   */
  capa?: (number | null) | Media;
  /**
   * Ilustração usada quando não há imagem de capa.
   */
  tema?: ('familia' | 'maos' | 'cidade' | 'encontro' | 'escudo' | 'doc') | null;
  autor?: string | null;
  destaque?: boolean | null;
  data?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Imagens e PDFs. Imagem de menor identificável exige cuidado (LGPD/ECA).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Descreva a imagem para leitores de tela.
   */
  alt: string;
  /**
   * Autoria/fonte da imagem.
   */
  credito?: string | null;
  /**
   * Por padrão NÃO publique imagem de criança/adolescente identificável. Marque apenas se houver termo de consentimento assinado.
   */
  consentimentoMenor?: boolean | null;
  /**
   * Obrigatório quando o consentimento estiver marcado (nº/arquivo do termo).
   */
  referenciaConsentimento?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Calendário, pautas e atas das reuniões.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reunioes".
 */
export interface Reunioe {
  id: number;
  /**
   * Ex.: "Reunião Ordinária — Março/2026".
   */
  titulo: string;
  data: string;
  tipo: 'ordinaria' | 'extraordinaria' | 'publica' | 'reservada';
  local?: string | null;
  pauta?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Anexe o PDF da ata aprovada, quando disponível.
   */
  ata?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Atos normativos do conselho. Também publicados na Tribuna do Norte.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resolucoes".
 */
export interface Resolucoe {
  id: number;
  /**
   * Ex.: "01/2026".
   */
  numero: string;
  titulo: string;
  data?: string | null;
  arquivo?: (number | null) | Media;
  /**
   * Opcional. URL da publicação oficial.
   */
  linkTribuna?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Chamamentos, processos do conselho tutelar e demais editais.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "editais".
 */
export interface Editai {
  id: number;
  /**
   * Ex.: "01/2026".
   */
  numero?: string | null;
  titulo: string;
  tipo: 'chamamento' | 'conselho_tutelar' | 'fmdca' | 'outro';
  data?: string | null;
  /**
   * Data limite para inscrição/manifestação, quando houver.
   */
  prazo?: string | null;
  arquivo?: (number | null) | Media;
  /**
   * Opcional. URL da publicação oficial.
   */
  linkTribuna?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Registro e acompanhamento de organizações da área da infância (arts. 90 e 91 do ECA).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entidades".
 */
export interface Entidade {
  id: number;
  nome: string;
  area?: ('educacao' | 'saude' | 'cultura_esporte' | 'assistencia' | 'acolhimento' | 'outro') | null;
  /**
   * Ex.: "Registro nº 05/2025".
   */
  registro?: string | null;
  validade?: string | null;
  /**
   * Certificado de registro, estatuto, etc.
   */
  documentos?: (number | Media)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Pontos da rede de proteção exibidos no mapa e na lista acessível da página Ajuda.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rede-protecao".
 */
export interface RedeProtecao {
  id: number;
  nome: string;
  tipo: 'ct' | 'cras' | 'creas' | 'casa' | 'outro';
  endereco?: string | null;
  telefone?: string | null;
  email?: string | null;
  horario?: string | null;
  /**
   * Ex.: plantão fora do horário, regras de atendimento.
   */
  obs?: string | null;
  /**
   * Coordenada para o mapa (ex.: -22.9239). [A CONFIRMAR] se ausente.
   */
  lat?: number | null;
  /**
   * Coordenada para o mapa (ex.: -45.4617).
   */
  lng?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Vozes exibidas no carrossel da página inicial.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "depoimentos".
 */
export interface Depoimento {
  id: number;
  frase: string;
  autor: string;
  /**
   * Ex.: "Presidente do CMDCA · biênio 2025–2027".
   */
  papel?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Slides do banner principal da página inicial. Ordene pelo campo "Ordem".
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destaques".
 */
export interface Destaque {
  id: number;
  /**
   * Texto curto acima do título. Ex.: "Conferência 2026".
   */
  kicker?: string | null;
  titulo: string;
  texto?: string | null;
  cta?: {
    label?: string | null;
    /**
     * Ex.: "/transparencia" ou "https://...".
     */
    href?: string | null;
  };
  /**
   * Ilustração autoral exibida no slide.
   */
  tema?: ('familia' | 'maos' | 'cidade' | 'encontro' | 'escudo' | 'doc') | null;
  ordem?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Perguntas frequentes exibidas nas páginas (Ajuda, FMDCA, etc.).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  pergunta: string;
  resposta: string;
  contexto?: ('ajuda' | 'fmdca' | 'geral') | null;
  ordem?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Editor: CRUD de conteúdo. Administrador: acesso total (inclui Usuários e Configurações).
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'noticias';
        value: number | Noticia;
      } | null)
    | ({
        relationTo: 'reunioes';
        value: number | Reunioe;
      } | null)
    | ({
        relationTo: 'resolucoes';
        value: number | Resolucoe;
      } | null)
    | ({
        relationTo: 'editais';
        value: number | Editai;
      } | null)
    | ({
        relationTo: 'entidades';
        value: number | Entidade;
      } | null)
    | ({
        relationTo: 'rede-protecao';
        value: number | RedeProtecao;
      } | null)
    | ({
        relationTo: 'depoimentos';
        value: number | Depoimento;
      } | null)
    | ({
        relationTo: 'destaques';
        value: number | Destaque;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticias_select".
 */
export interface NoticiasSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  categoria?: T;
  resumo?: T;
  corpo?: T;
  capa?: T;
  tema?: T;
  autor?: T;
  destaque?: T;
  data?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reunioes_select".
 */
export interface ReunioesSelect<T extends boolean = true> {
  titulo?: T;
  data?: T;
  tipo?: T;
  local?: T;
  pauta?: T;
  ata?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resolucoes_select".
 */
export interface ResolucoesSelect<T extends boolean = true> {
  numero?: T;
  titulo?: T;
  data?: T;
  arquivo?: T;
  linkTribuna?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "editais_select".
 */
export interface EditaisSelect<T extends boolean = true> {
  numero?: T;
  titulo?: T;
  tipo?: T;
  data?: T;
  prazo?: T;
  arquivo?: T;
  linkTribuna?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entidades_select".
 */
export interface EntidadesSelect<T extends boolean = true> {
  nome?: T;
  area?: T;
  registro?: T;
  validade?: T;
  documentos?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rede-protecao_select".
 */
export interface RedeProtecaoSelect<T extends boolean = true> {
  nome?: T;
  tipo?: T;
  endereco?: T;
  telefone?: T;
  email?: T;
  horario?: T;
  obs?: T;
  lat?: T;
  lng?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "depoimentos_select".
 */
export interface DepoimentosSelect<T extends boolean = true> {
  frase?: T;
  autor?: T;
  papel?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destaques_select".
 */
export interface DestaquesSelect<T extends boolean = true> {
  kicker?: T;
  titulo?: T;
  texto?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  tema?: T;
  ordem?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  pergunta?: T;
  resposta?: T;
  contexto?: T;
  ordem?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credito?: T;
  consentimentoMenor?: T;
  referenciaConsentimento?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Contatos, redes, parâmetros do FMDCA e base legal. Visível somente a administradores.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configuracoes".
 */
export interface Configuracoe {
  id: number;
  nomeConselho?: string | null;
  municipio?: string | null;
  diretoria?: {
    gestaoLabel?: string | null;
    presidenteNome?: string | null;
    presidenteCargo?: string | null;
    viceNome?: string | null;
    viceCargo?: string | null;
  };
  contato?: {
    email?: string | null;
    telefone?: string | null;
    cep?: string | null;
    casaConselhosTelefone?: string | null;
    casaConselhosEndereco?: string | null;
    assessora?: string | null;
  };
  redes?: {
    instagramHandle?: string | null;
    instagramUrl?: string | null;
  };
  fmdca?: {
    cnpj?: string | null;
    conta?: string | null;
    /**
     * Percentual ILUSTRATIVO usado no simulador. Confirme os limites legais com seu contador.
     */
    percentualDeducaoIR?: number | null;
    comoDestinar?: string | null;
  };
  baseLegal?: {
    leiCMDCA?: string | null;
    leiFMDCA?: string | null;
    regimento?: string | null;
  };
  /**
   * Onde os atos oficiais do conselho são publicados.
   */
  tribunaUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Quais blocos aparecem na home e em que ordem.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-inicial".
 */
export interface PaginaInicial {
  id: number;
  /**
   * Arraste para reordenar. Desmarque "Ativo" para ocultar sem remover.
   */
  blocos?:
    | {
        tipo: 'slider' | 'sobre' | 'atalhos' | 'indicadores' | 'vozes' | 'noticias';
        ativo?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Números do painel "O conselho em números" e dos gráficos. Editar aqui atualiza contadores e gráficos no site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "indicadores".
 */
export interface Indicadore {
  id: number;
  alcancados?: number | null;
  projetos?: number | null;
  entidades?: number | null;
  reunioesNoAno?: number | null;
  /**
   * Ex.: projetos apoiados por ano.
   */
  serieAnual?:
    | {
        ano: string;
        valor: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Percentual de recursos aplicados por área. Some ~100%.
   */
  aplicacaoPorArea?:
    | {
        area: string;
        percentual: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Aviso exibido junto ao painel enquanto os números forem ilustrativos.
   */
  observacao?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configuracoes_select".
 */
export interface ConfiguracoesSelect<T extends boolean = true> {
  nomeConselho?: T;
  municipio?: T;
  diretoria?:
    | T
    | {
        gestaoLabel?: T;
        presidenteNome?: T;
        presidenteCargo?: T;
        viceNome?: T;
        viceCargo?: T;
      };
  contato?:
    | T
    | {
        email?: T;
        telefone?: T;
        cep?: T;
        casaConselhosTelefone?: T;
        casaConselhosEndereco?: T;
        assessora?: T;
      };
  redes?:
    | T
    | {
        instagramHandle?: T;
        instagramUrl?: T;
      };
  fmdca?:
    | T
    | {
        cnpj?: T;
        conta?: T;
        percentualDeducaoIR?: T;
        comoDestinar?: T;
      };
  baseLegal?:
    | T
    | {
        leiCMDCA?: T;
        leiFMDCA?: T;
        regimento?: T;
      };
  tribunaUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-inicial_select".
 */
export interface PaginaInicialSelect<T extends boolean = true> {
  blocos?:
    | T
    | {
        tipo?: T;
        ativo?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "indicadores_select".
 */
export interface IndicadoresSelect<T extends boolean = true> {
  alcancados?: T;
  projetos?: T;
  entidades?: T;
  reunioesNoAno?: T;
  serieAnual?:
    | T
    | {
        ano?: T;
        valor?: T;
        id?: T;
      };
  aplicacaoPorArea?:
    | T
    | {
        area?: T;
        percentual?: T;
        id?: T;
      };
  observacao?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}