/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    noticias: Noticia;
    reunioes: Reunioe;
    resolucoes: Resolucoe;
    editais: Editai;
    entidades: Entidade;
    'rede-protecao': RedeProtecao;
    depoimentos: Depoimento;
    destaques: Destaque;
    faq: Faq;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    noticias: NoticiasSelect<false> | NoticiasSelect<true>;
    reunioes: ReunioesSelect<false> | ReunioesSelect<true>;
    resolucoes: ResolucoesSelect<false> | ResolucoesSelect<true>;
    editais: EditaisSelect<false> | EditaisSelect<true>;
    entidades: EntidadesSelect<false> | EntidadesSelect<true>;
    'rede-protecao': RedeProtecaoSelect<false> | RedeProtecaoSelect<true>;
    depoimentos: DepoimentosSelect<false> | DepoimentosSelect<true>;
    destaques: DestaquesSelect<false> | DestaquesSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    configuracoes: Configuracoe;
    'pagina-inicial': PaginaInicial;
    indicadores: Indicadore;
  };
  globalsSelect: {
    configuracoes: ConfiguracoesSelect<false> | ConfiguracoesSelect<true>;
    'pagina-inicial': PaginaInicialSelect<false> | PaginaInicialSelect<true>;
    indicadores: IndicadoresSelect<false> | IndicadoresSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Prepare o texto como rascunho. Jurídico ou administração conferem e publicam.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticias".
 */
export interface Noticia {
  id: number;
  title: string;
  /**
   * Gerado automaticamente a partir do título. Edite apenas se necessário — altera a URL pública.
   */
  slug: string;
  categoria: 'noticia' | 'conferencia' | 'evento' | 'gestao' | 'fmdca' | 'orientacao' | 'nota-tecnica';
  /**
   * Chamada objetiva entre 40 e 320 caracteres.
   */
  resumo: string;
  corpo: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Somente JPG, PNG, WebP ou GIF. PDF não pode ser usado como capa.
   */
  capa?: (number | null) | Media;
  /**
   * Usado quando não houver capa.
   */
  tema?: ('familia' | 'maos' | 'cidade' | 'encontro' | 'escudo' | 'doc') | null;
  autor: string;
  destaque?: boolean | null;
  data: string;
  /**
   * Controle interno. Estes dados não aparecem no site público.
   */
  controleEditorial: {
    /**
     * Órgão, processo, documento ou página oficial consultada.
     */
    fonte?: string | null;
    /**
     * Opcional. Use uma página oficial com https://.
     */
    fonteURL?: string | null;
    verificadoEm?: string | null;
    statusRevisao: 'pendente' | 'aprovada' | 'dispensada';
    revisadoPor?: (number | null) | User;
    /**
     * Pendências, justificativas e instruções para a próxima revisão.
     */
    observacoesInternas?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Imagens e PDFs públicos. Nunca envie documentos com dados pessoais, termos de autorização ou conteúdo sigiloso.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Obrigatório para imagens. Em PDFs, informe apenas se ajudar a identificar o documento.
   */
  alt?: string | null;
  /**
   * Autoria que pode aparecer junto da imagem.
   */
  credito?: string | null;
  /**
   * Marque quando rosto, voz, nome, uniforme ou contexto permitir identificação.
   */
  envolveMenorIdentificavel?: boolean | null;
  /**
   * Marque somente após conferir o termo assinado e sua validade para publicação.
   */
  consentimentoMenor?: boolean | null;
  /**
   * Número de processo/arquivo interno. Não envie o termo para esta biblioteca pública.
   */
  referenciaConsentimento?: string | null;
  /**
   * Controle interno. Estes dados não aparecem no site público.
   */
  controleEditorial: {
    /**
     * Órgão, processo, documento ou página oficial consultada.
     */
    fonte?: string | null;
    /**
     * Opcional. Use uma página oficial com https://.
     */
    fonteURL?: string | null;
    verificadoEm?: string | null;
    statusRevisao: 'pendente' | 'aprovada' | 'dispensada';
    revisadoPor?: (number | null) | User;
    /**
     * Pendências, justificativas e instruções para a próxima revisão.
     */
    observacoesInternas?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Contas do painel. Mantenha sempre pelo menos dois administradores ativos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Editor prepara rascunhos. Jurídico revisa e publica. Administrador também gerencia contas e exclusões.
   */
  role: 'admin' | 'editor' | 'juridico';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Cadastre natureza, acesso, forma de participação, pauta e ata separadamente.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reunioes".
 */
export interface Reunioe {
  id: number;
  /**
   * Ex.: “Reunião Ordinária — março de 2026”.
   */
  titulo: string;
  data: string;
  /**
   * Formato 24 horas, por exemplo 14:30.
   */
  hora: string;
  tipo: 'ordinaria' | 'extraordinaria';
  /**
   * Reuniões reservadas nunca são retornadas pela API pública.
   */
  acesso: 'publica' | 'reservada';
  modalidade: 'presencial' | 'online' | 'hibrida';
  local?: string | null;
  linkTransmissao?: string | null;
  pauta?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Anexe somente depois da aprovação da ata.
   */
  ata?: (number | null) | Media;
  /**
   * Controle interno. Estes dados não aparecem no site público.
   */
  controleEditorial: {
    /**
     * Órgão, processo, documento ou página oficial consultada.
     */
    fonte?: string | null;
    /**
     * Opcional. Use uma página oficial com https://.
     */
    fonteURL?: string | null;
    verificadoEm?: string | null;
    statusRevisao: 'pendente' | 'aprovada' | 'dispensada';
    revisadoPor?: (number | null) | User;
    /**
     * Pendências, justificativas e instruções para a próxima revisão.
     */
    observacoesInternas?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Atos normativos do conselho. O jurídico confere número, vigência, fonte e PDF antes da publicação.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resolucoes".
 */
export interface Resolucoe {
  id: number;
  /**
   * Identificador oficial, exatamente como consta no ato. Ex.: “01/2026”.
   */
  numero: string;
  titulo: string;
  data: string;
  /**
   * Atualize quando o ato for alterado, revogado ou perder efeito.
   */
  situacaoJuridica: 'vigente' | 'alterada' | 'revogada' | 'sem_efeito';
  /**
   * A publicação exige o documento oficial em formato PDF.
   */
  arquivo: number | Media;
  /**
   * Relacione os atos anteriores afetados por esta resolução, quando houver.
   */
  retifica?: (number | Resolucoe)[] | null;
  /**
   * Opcional. URL completa da publicação oficial.
   */
  linkTribuna?: string | null;
  /**
   * Controle interno. Estes dados não aparecem no site público.
   */
  controleEditorial: {
    /**
     * Órgão, processo, documento ou página oficial consultada.
     */
    fonte?: string | null;
    /**
     * Opcional. Use uma página oficial com https://.
     */
    fonteURL?: string | null;
    verificadoEm?: string | null;
    statusRevisao: 'pendente' | 'aprovada' | 'dispensada';
    revisadoPor?: (number | null) | User;
    /**
     * Pendências, justificativas e instruções para a próxima revisão.
     */
    observacoesInternas?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Chamamentos e processos oficiais. O jurídico confere prazo, situação, fonte e PDF antes da publicação.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "editais".
 */
export interface Editai {
  id: number;
  /**
   * Identificador oficial, exatamente como consta no edital. Ex.: “01/2026”.
   */
  numero: string;
  titulo: string;
  tipo: 'chamamento' | 'conselho_tutelar' | 'fmdca' | 'outro';
  situacaoJuridica: 'vigente' | 'encerrado' | 'suspenso' | 'revogado' | 'anulado';
  data: string;
  /**
   * Data limite, quando houver. Nunca pode anteceder a publicação.
   */
  prazo?: string | null;
  /**
   * A publicação exige o edital oficial em formato PDF.
   */
  arquivo: number | Media;
  /**
   * Relacione os editais anteriores afetados por esta retificação.
   */
  retifica?: (number | Editai)[] | null;
  /**
   * Opcional. URL completa da publicação oficial.
   */
  linkTribuna?: string | null;
  /**
   * Controle interno. Estes dados não aparecem no site público.
   */
  controleEditorial: {
    /**
     * Órgão, processo, documento ou página oficial consultada.
     */
    fonte?: string | null;
    /**
     * Opcional. Use uma página oficial com https://.
     */
    fonteURL?: string | null;
    verificadoEm?: string | null;
    statusRevisao: 'pendente' | 'aprovada' | 'dispensada';
    revisadoPor?: (number | null) | User;
    /**
     * Pendências, justificativas e instruções para a próxima revisão.
     */
    observacoesInternas?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Registro público de organizações da área da infância. Publique somente dados conferidos e documentos sem informação restrita.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entidades".
 */
export interface Entidade {
  id: number;
  nome: string;
  area: 'educacao' | 'saude' | 'cultura_esporte' | 'assistencia' | 'acolhimento' | 'outro';
  /**
   * Use o identificador oficial. Ex.: “Registro nº 05/2025”.
   */
  registro: string;
  validade: string;
  situacaoRegistro: 'ativo' | 'vencido' | 'suspenso' | 'cancelado';
  /**
   * Anexe certificado, resolução ou outro documento público. Não envie documentos com dados pessoais ou restritos.
   */
  documentos: (number | Media)[];
  /**
   * Controle interno. Estes dados não aparecem no site público.
   */
  controleEditorial: {
    /**
     * Órgão, processo, documento ou página oficial consultada.
     */
    fonte?: string | null;
    /**
     * Opcional. Use uma página oficial com https://.
     */
    fonteURL?: string | null;
    verificadoEm?: string | null;
    statusRevisao: 'pendente' | 'aprovada' | 'dispensada';
    revisadoPor?: (number | null) | User;
    /**
     * Pendências, justificativas e instruções para a próxima revisão.
     */
    observacoesInternas?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Serviços exibidos no mapa e na lista acessível da página Ajuda. Confirme os canais diretamente com o órgão antes de publicar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rede-protecao".
 */
export interface RedeProtecao {
  id: number;
  nome: string;
  tipo: 'ct' | 'cras' | 'creas' | 'casa' | 'outro';
  /**
   * Inclua logradouro, número, bairro e referência quando disponíveis.
   */
  endereco?: string | null;
  /**
   * Informe DDD e identifique WhatsApp ou plantão.
   */
  telefone?: string | null;
  email?: string | null;
  /**
   * Ex.: “segunda a sexta, das 8h às 17h”.
   */
  horario?: string | null;
  /**
   * Ex.: plantão fora do horário ou regras de atendimento.
   */
  obs?: string | null;
  /**
   * Coordenada entre -90 e 90. Ex.: -22.9239.
   */
  lat?: number | null;
  /**
   * Coordenada entre -180 e 180. Ex.: -45.4617.
   */
  lng?: number | null;
  /**
   * Controle interno. Estes dados não aparecem no site público.
   */
  controleEditorial: {
    /**
     * Órgão, processo, documento ou página oficial consultada.
     */
    fonte?: string | null;
    /**
     * Opcional. Use uma página oficial com https://.
     */
    fonteURL?: string | null;
    verificadoEm?: string | null;
    statusRevisao: 'pendente' | 'aprovada' | 'dispensada';
    revisadoPor?: (number | null) | User;
    /**
     * Pendências, justificativas e instruções para a próxima revisão.
     */
    observacoesInternas?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Vozes exibidas na página inicial. Registre a origem e só publique após confirmar a autorização.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "depoimentos".
 */
export interface Depoimento {
  id: number;
  /**
   * Transcreva fielmente e evite dados pessoais desnecessários.
   */
  frase: string;
  /**
   * Use nome, iniciais ou descrição autorizada.
   */
  autor: string;
  /**
   * Ex.: “Presidente do CMDCA · biênio 2025–2027”.
   */
  papel?: string | null;
  /**
   * Controle interno. Informe onde o termo ou consentimento está arquivado, sem inserir dados pessoais sensíveis.
   */
  origem?: string | null;
  /**
   * Somente jurídico ou administração pode confirmar esta autorização.
   */
  autorizacaoPublicacao?: boolean | null;
  /**
   * Controle interno. Estes dados não aparecem no site público.
   */
  controleEditorial: {
    /**
     * Órgão, processo, documento ou página oficial consultada.
     */
    fonte?: string | null;
    /**
     * Opcional. Use uma página oficial com https://.
     */
    fonteURL?: string | null;
    verificadoEm?: string | null;
    statusRevisao: 'pendente' | 'aprovada' | 'dispensada';
    revisadoPor?: (number | null) | User;
    /**
     * Pendências, justificativas e instruções para a próxima revisão.
     */
    observacoesInternas?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Slides do banner principal. Editor prepara o rascunho; jurídico ou administração publica.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destaques".
 */
export interface Destaque {
  id: number;
  /**
   * Texto curto acima do título. Ex.: “Conferência 2026”.
   */
  kicker?: string | null;
  titulo: string;
  texto?: string | null;
  /**
   * Preencha texto e link juntos, ou deixe os dois campos vazios.
   */
  cta?: {
    label?: string | null;
    /**
     * Ex.: “/transparencia” ou “https://...”.
     */
    href?: string | null;
  };
  /**
   * Ilustração autoral exibida no slide.
   */
  tema?: ('familia' | 'maos' | 'cidade' | 'encontro' | 'escudo' | 'doc') | null;
  ordem: number;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Respostas exibidas em Ajuda e FMDCA. Registre a fonte usada e revise sempre que a orientação mudar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  pergunta: string;
  resposta: string;
  contexto: 'ajuda' | 'fmdca' | 'geral';
  ordem: number;
  /**
   * Controle interno. Estes dados não aparecem no site público.
   */
  controleEditorial: {
    /**
     * Órgão, processo, documento ou página oficial consultada.
     */
    fonte?: string | null;
    /**
     * Opcional. Use uma página oficial com https://.
     */
    fonteURL?: string | null;
    verificadoEm?: string | null;
    statusRevisao: 'pendente' | 'aprovada' | 'dispensada';
    revisadoPor?: (number | null) | User;
    /**
     * Pendências, justificativas e instruções para a próxima revisão.
     */
    observacoesInternas?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'noticias';
        value: number | Noticia;
      } | null)
    | ({
        relationTo: 'reunioes';
        value: number | Reunioe;
      } | null)
    | ({
        relationTo: 'resolucoes';
        value: number | Resolucoe;
      } | null)
    | ({
        relationTo: 'editais';
        value: number | Editai;
      } | null)
    | ({
        relationTo: 'entidades';
        value: number | Entidade;
      } | null)
    | ({
        relationTo: 'rede-protecao';
        value: number | RedeProtecao;
      } | null)
    | ({
        relationTo: 'depoimentos';
        value: number | Depoimento;
      } | null)
    | ({
        relationTo: 'destaques';
        value: number | Destaque;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticias_select".
 */
export interface NoticiasSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  categoria?: T;
  resumo?: T;
  corpo?: T;
  capa?: T;
  tema?: T;
  autor?: T;
  destaque?: T;
  data?: T;
  controleEditorial?:
    | T
    | {
        fonte?: T;
        fonteURL?: T;
        verificadoEm?: T;
        statusRevisao?: T;
        revisadoPor?: T;
        observacoesInternas?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reunioes_select".
 */
export interface ReunioesSelect<T extends boolean = true> {
  titulo?: T;
  data?: T;
  hora?: T;
  tipo?: T;
  acesso?: T;
  modalidade?: T;
  local?: T;
  linkTransmissao?: T;
  pauta?: T;
  ata?: T;
  controleEditorial?:
    | T
    | {
        fonte?: T;
        fonteURL?: T;
        verificadoEm?: T;
        statusRevisao?: T;
        revisadoPor?: T;
        observacoesInternas?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resolucoes_select".
 */
export interface ResolucoesSelect<T extends boolean = true> {
  numero?: T;
  titulo?: T;
  data?: T;
  situacaoJuridica?: T;
  arquivo?: T;
  retifica?: T;
  linkTribuna?: T;
  controleEditorial?:
    | T
    | {
        fonte?: T;
        fonteURL?: T;
        verificadoEm?: T;
        statusRevisao?: T;
        revisadoPor?: T;
        observacoesInternas?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "editais_select".
 */
export interface EditaisSelect<T extends boolean = true> {
  numero?: T;
  titulo?: T;
  tipo?: T;
  situacaoJuridica?: T;
  data?: T;
  prazo?: T;
  arquivo?: T;
  retifica?: T;
  linkTribuna?: T;
  controleEditorial?:
    | T
    | {
        fonte?: T;
        fonteURL?: T;
        verificadoEm?: T;
        statusRevisao?: T;
        revisadoPor?: T;
        observacoesInternas?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entidades_select".
 */
export interface EntidadesSelect<T extends boolean = true> {
  nome?: T;
  area?: T;
  registro?: T;
  validade?: T;
  situacaoRegistro?: T;
  documentos?: T;
  controleEditorial?:
    | T
    | {
        fonte?: T;
        fonteURL?: T;
        verificadoEm?: T;
        statusRevisao?: T;
        revisadoPor?: T;
        observacoesInternas?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rede-protecao_select".
 */
export interface RedeProtecaoSelect<T extends boolean = true> {
  nome?: T;
  tipo?: T;
  endereco?: T;
  telefone?: T;
  email?: T;
  horario?: T;
  obs?: T;
  lat?: T;
  lng?: T;
  controleEditorial?:
    | T
    | {
        fonte?: T;
        fonteURL?: T;
        verificadoEm?: T;
        statusRevisao?: T;
        revisadoPor?: T;
        observacoesInternas?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "depoimentos_select".
 */
export interface DepoimentosSelect<T extends boolean = true> {
  frase?: T;
  autor?: T;
  papel?: T;
  origem?: T;
  autorizacaoPublicacao?: T;
  controleEditorial?:
    | T
    | {
        fonte?: T;
        fonteURL?: T;
        verificadoEm?: T;
        statusRevisao?: T;
        revisadoPor?: T;
        observacoesInternas?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destaques_select".
 */
export interface DestaquesSelect<T extends boolean = true> {
  kicker?: T;
  titulo?: T;
  texto?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  tema?: T;
  ordem?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  pergunta?: T;
  resposta?: T;
  contexto?: T;
  ordem?: T;
  controleEditorial?:
    | T
    | {
        fonte?: T;
        fonteURL?: T;
        verificadoEm?: T;
        statusRevisao?: T;
        revisadoPor?: T;
        observacoesInternas?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credito?: T;
  envolveMenorIdentificavel?: T;
  consentimentoMenor?: T;
  referenciaConsentimento?: T;
  controleEditorial?:
    | T
    | {
        fonte?: T;
        fonteURL?: T;
        verificadoEm?: T;
        statusRevisao?: T;
        revisadoPor?: T;
        observacoesInternas?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Dados institucionais e legais. Alterações são salvas como rascunho e só entram no site depois da publicação.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configuracoes".
 */
export interface Configuracoe {
  id: number;
  nomeConselho: string;
  municipio: string;
  diretoria?: {
    gestaoLabel?: string | null;
    presidenteNome?: string | null;
    presidenteCargo?: string | null;
    viceNome?: string | null;
    viceCargo?: string | null;
  };
  contato: {
    email: string;
    telefone?: string | null;
    cep?: string | null;
    casaConselhosTelefone?: string | null;
    casaConselhosEndereco?: string | null;
    assessora?: string | null;
  };
  redes?: {
    instagramHandle?: string | null;
    instagramUrl?: string | null;
  };
  /**
   * Dados bancários ficam ocultos da API pública enquanto não forem confirmados.
   */
  fmdca?: {
    dadosBancariosConfirmados?: boolean | null;
    cnpj?: string | null;
    conta?: string | null;
    /**
     * Confirme a regra aplicável e a data de verificação antes de publicar.
     */
    percentualDeducaoIR?: number | null;
    comoDestinar?: string | null;
  };
  baseLegal: {
    leiCMDCA: string;
    leiFMDCA: string;
    regimento?: string | null;
  };
  /**
   * Endereço usado para consultar publicações oficiais.
   */
  tribunaUrl?: string | null;
  /**
   * Controle interno. Estes dados não aparecem no site público.
   */
  controleEditorial: {
    /**
     * Órgão, processo, documento ou página oficial consultada.
     */
    fonte?: string | null;
    /**
     * Opcional. Use uma página oficial com https://.
     */
    fonteURL?: string | null;
    verificadoEm?: string | null;
    statusRevisao: 'pendente' | 'aprovada' | 'dispensada';
    revisadoPor?: (number | null) | User;
    /**
     * Pendências, justificativas e instruções para a próxima revisão.
     */
    observacoesInternas?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Organize os blocos. Editor salva rascunho; jurídico ou administração publicam.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-inicial".
 */
export interface PaginaInicial {
  id: number;
  /**
   * Arraste para reordenar. Desative para ocultar sem perder a configuração.
   */
  blocos?:
    | {
        tipo: 'slider' | 'sobre' | 'atalhos' | 'indicadores' | 'vozes' | 'noticias';
        ativo?: boolean | null;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Os números ficam ocultos do público até “Publicar indicadores” ser marcado e a fonte ser aprovada.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "indicadores".
 */
export interface Indicadore {
  id: number;
  /**
   * Deixe desligado até conferir período, fonte e todos os totais.
   */
  publicar?: boolean | null;
  /**
   * Ex.: janeiro a dezembro de 2025.
   */
  periodoReferencia?: string | null;
  fonte?: string | null;
  fonteURL?: string | null;
  verificadoEm?: string | null;
  statusRevisao?: ('pendente' | 'aprovada') | null;
  observacoesInternas?: string | null;
  alcancados?: number | null;
  projetos?: number | null;
  entidades?: number | null;
  reunioesNoAno?: number | null;
  serieAnual?:
    | {
        ano: string;
        valor: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Quando preenchidos, os percentuais devem somar 100%.
   */
  aplicacaoPorArea?:
    | {
        area: string;
        percentual: number;
        id?: string | null;
      }[]
    | null;
  observacao?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configuracoes_select".
 */
export interface ConfiguracoesSelect<T extends boolean = true> {
  nomeConselho?: T;
  municipio?: T;
  diretoria?:
    | T
    | {
        gestaoLabel?: T;
        presidenteNome?: T;
        presidenteCargo?: T;
        viceNome?: T;
        viceCargo?: T;
      };
  contato?:
    | T
    | {
        email?: T;
        telefone?: T;
        cep?: T;
        casaConselhosTelefone?: T;
        casaConselhosEndereco?: T;
        assessora?: T;
      };
  redes?:
    | T
    | {
        instagramHandle?: T;
        instagramUrl?: T;
      };
  fmdca?:
    | T
    | {
        dadosBancariosConfirmados?: T;
        cnpj?: T;
        conta?: T;
        percentualDeducaoIR?: T;
        comoDestinar?: T;
      };
  baseLegal?:
    | T
    | {
        leiCMDCA?: T;
        leiFMDCA?: T;
        regimento?: T;
      };
  tribunaUrl?: T;
  controleEditorial?:
    | T
    | {
        fonte?: T;
        fonteURL?: T;
        verificadoEm?: T;
        statusRevisao?: T;
        revisadoPor?: T;
        observacoesInternas?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-inicial_select".
 */
export interface PaginaInicialSelect<T extends boolean = true> {
  blocos?:
    | T
    | {
        tipo?: T;
        ativo?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "indicadores_select".
 */
export interface IndicadoresSelect<T extends boolean = true> {
  publicar?: T;
  periodoReferencia?: T;
  fonte?: T;
  fonteURL?: T;
  verificadoEm?: T;
  statusRevisao?: T;
  observacoesInternas?: T;
  alcancados?: T;
  projetos?: T;
  entidades?: T;
  reunioesNoAno?: T;
  serieAnual?:
    | T
    | {
        ano?: T;
        valor?: T;
        id?: T;
      };
  aplicacaoPorArea?:
    | T
    | {
        area?: T;
        percentual?: T;
        id?: T;
      };
  observacao?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}